# IMAGEN MODELO - SE SACA DE DOCKERHUB
FROM eclipse-temurin:17.0.15_6-jdk

# INFORMAR EL PUERTO DONDE SE EJECUTA EL CONTENEDOR (INFORMATIVO)
EXPOSE 8080

# DEFINIR DIRECTORIO RAIZ DE NUESTRO CONTENEDOR
WORKDIR /root

# COPIAR Y PEGAR ARCHIVOS DENTRO DEL CONTENEDOR - 1. DEPENDECIAS - 2.RUTA DEL .EXE DE MAVEN - 3.EL .EXE DE MAVEN PERO DE LINUX
COPY ./pom.xml /root
COPY ./.mvn /root/.mvn
COPY ./mvnw /root

# DESCARGAR LAS DEPENDENCIAS
RUN ./mvnw dependency:go-offline

# COPIAR EL CODIGO FUENTE DENTRO DEL CONTENEDOR
COPY ./src /root/src

# CONSTRUIR NUESTRA APLICACION - "-DskipTests" PARA OMITIR LOS TEST
RUN ./mvnw clean install -DskipTests

# LEVANTAR NUESTRA APLICACION CUANDO EL CONTENEDOR INICIE
ENTRYPOINT ["java","-jar","/root/target/blog-jwt_mysql-0.0.1-SNAPSHOT.jar"]